version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - A-dependency
  - I-dependency-gardening
  versioning-strategy: increase
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - A-docker-image
  - I-dependency-gardening
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-major']
